name: Scheduled Jobs #액션 이름

on:
  schedule:
    - cron: '9 * * * *' # 언제 이 액션이 실행될 것인지

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build