name: Scheduled Jobs

on:
  schedule:
    - cron: '7 * * * *'

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: taeyang-s-playGround/1Day-1Commit-bot
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: 1Day-1Commit-bot

      - name: Set execute permission for gradlew
        run: chmod +x 1Day-1Commit-bot/gradlew  # 경로를 수정

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Add date and push
        run: |
          cd 1Day-1Commit-bot
          date >> date.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "feat :: quotes"
          git push